package:
  name: thrustrtc
  version: 0.2.0

source:
  git_rev: 0.2.0
  git_url: https://github.com/fynv/ThrustRTC.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  imports: 
    - ThrustRTC

about:
  home: https://github.com/fynv/ThrustRTC
  license: Anti-996
  summary: CUDA tool set for non-C++ languages that provides similar functionality like Thrust, with NVRTC at its core.