name: Conda Ubuntu Publishment

on:
  push:
    branches: [ master ]

jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:    
        submodules: true

    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        subDir: 'conda_ubuntu'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
