name: Python Package using Conda

on: 
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true    
        
    - name: conda build/publish
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: 'conda_windows'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'win-64'
    
